#!/bin/bash

set -o errexit
set -o nounset

python /app/manage.py collectstatic  \
  --no-input  \
  -i django_extensions \
  -i '*.coffee' \
  -i '*.rb' \
  -i '*.scss' \
  -i '*.less' \
  -i '*.sass'
python /app/manage.py migrate --no-input
python /app/manage.py touch_superuser

gunicorn -c gunicorn.ini config.wsgi
