# -*- coding: utf-8 -*-
from src.common.domain.enums.auth import AuthenticationMethod
from src.common.domain.enums.locales import CountryIsoCode, Language, TimeZone

DEFAULT_PENDING_ACTION_EXPIRATION_IN_MINUTES = 15
DEFAULT_PENDING_ACTION_USAGE_LIMIT = 1
DEFAULT_PENDING_ACTION_SESSION_USAGE_LIMIT = 3

INSTANCE_DELETED_RESPONSE = ''

DEFAULT_MEMBERSHIP_PLAN_GRACE_PERIOD_IN_DAYS = 5
DEFAULT_MEMBERSHIP_PLAN_STUDENTS_NUMBER = 1
DEFAULT_MEMBERSHIP_PLAN_PASSES_NUMBER = 4
DEFAULT_MEMBERSHIP_PLAN_VALIDITY_DAYS = 90
DEFAULT_MEMBERSHIP_PLAN_TIME_MULTIPLIER = 1
DEFAULT_SESSION_TOLERANCE_IN_MINUTES = 20

ONE_WEEK_DAYS = 7
ONE_MONTH = 1
ONE_DAY = 1

DEFAULT_NEXT_SESSIONS_IN_MINUTES = 12 * 60  # 12 hours

DEFAULT_TIMEZONE = TimeZone.MEXICO_CITY
DEFAULT_LANGUAGE = Language.ES

DEFAULT_MEXICO_PREFIX = 1


DEFAULT_INITIAL_PAGE = 1
DEFAULT_PAGINATION_PAGE_SIZE = 25
DEFAULT_PAGINATION_LOOKUP_FIELD = '-created_at'


PHONE_NUMBER_PREFIXES_MAP = {
    CountryIsoCode.MEXICO: 1,
    CountryIsoCode.BRAZIL: 9,
}
