# -*- coding: utf-8 -*-
from src.common.domain.enums.locales import Language, TimeZone

DEFAULT_PENDING_ACTION_EXPIRATION_IN_MINUTES = 15
DEFAULT_PENDING_ACTION_USAGE_LIMIT = 1
DEFAULT_PENDING_ACTION_SESSION_USAGE_LIMIT = 3
DEFAULT_REQUEST_TIMEOUT = 20

INSTANCE_DELETED_RESPONSE = ''

ONE_WEEK_DAYS = 7
ONE_MONTH = 1
ONE_DAY = 1

ONE_HOUR_IN_SECONDS = 60 * 60

DEFAULT_TIMEZONE = TimeZone.MEXICO_CITY
DEFAULT_LANGUAGE = Language.ES
